services:
  postgres:
    container_name: db
    image: postgres:latest
    ports:
    - "54321:5432"
    volumes:
    - data:/var/lib/postgresql/data
    # - /etc/localtime:/etc/localtime:ro
    # - /etc/timezone:/etc/timezone:ro
    env_file:
    - .docker.env
    networks:
    - network_test

volumes:
  data:

networks:
  network_test:
    driver: bridge
